### ISSUE TITLE
Move Joss resources to a "paper" folder

### ISSUE THREAD

**Issue by henrykironde** [js2264/VplotR#2]
Make a folder called paper and move those related files to that folder.
Also include the other author. 
@nturaga Nitesh Turaga, unless there is a reason not to

**Comment by henrykironde** [comment]
About the author, there are no substantial commits from the author. In this case, you should not add the author. I have just checked the contributions.

**Comment by js2264** [comment]
I have moved the necessary files to `paper/` directory. I have also merged JOSS to master, not sure how to inform whedon about this change.

**Comment by js2264** [comment]
Regarding authors, I am not sure why the contributions summary from whedon ([https://github.com/openjournals/joss-reviews/issues/3009#issuecomment-773329604](https://github.com/openjournals/joss-reviews/issues/3009#issuecomment-773329604)) only show 2 commits from me... I am the only author of this package and have 50+ commits on this package.

Nitesh is not an author, he is a Bioconductor maintainer and only contributed to this repo to add it to Bioc release 3.12, so there is no reason to list him as an author
