### ISSUE TITLE
Render output correctly 

### ISSUE THREAD

**Issue by henrykironde** [js2264/VplotR#5]
For the first example, could you add  `p` to display the graph.

```R
data(MNase_sacCer3_Henikoff2011)
data(ABF1_sacCer3)
p <- plotVmat(
    x = MNase_sacCer3_Henikoff2011, 
    granges = ABF1_sacCer3
)
p # display the plot
```
 Could you remove the ## in the output. Unless it affects building docs

**Comment by js2264** [comment]
I have added`p` (though it does not affect the aspect of rendered README.md, since it's not actually processed, unlike an Rmd)

**Comment by js2264** [comment]
`##` at the beginning of lines delineate chunks of text output in R (as shown here: https://bookdown.org/yihui/rmarkdown-cookbook/chunk-styling.html#chunk-styling). I believe this is standard and should be kept as it is

**Comment by henrykironde** [comment]
Sounds good
